name = "closetcity"
pages_build_output_dir = "out"
compatibility_date = "2024-10-01"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "off"

[vars]
PROMPT_VERSION = "v1"

# Note: GEMINI_API_KEY should be set as a secret in Cloudflare Pages dashboard
# or via: wrangler pages secret put GEMINI_API_KEY --project-name closetcity
# Updated: 2025-09-24 - using static build approach

[[d1_databases]]
database_id = "58aa5cb8-32e5-4ee7-8b11-55edc3d261d6"
binding = "DB"
database_name = "closetcity-db"

[[r2_buckets]]
bucket_name = "closetcity-storage"
binding = "R2"

[[kv_namespaces]]
binding = "JOBS"
id = "fb3079a868274895b2386fcd4ad259cc"

[ai]
binding = "AI"

[env.production]

[env.production.placement]
mode = "smart"

[env.production.vars]
PROMPT_VERSION = "v1"
# GEMINI_API_KEY = "your-key-here"  # Uncomment and add your key for testing

# Note: Secrets (GEMINI_API_KEY, STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET)
# should be set in Cloudflare Pages Dashboard → Settings → Environment Variables
# as "Encrypted" variables for the Production environment
# If free tier has limitations, you may need to add GEMINI_API_KEY directly above

[[env.production.d1_databases]]
database_id = "58aa5cb8-32e5-4ee7-8b11-55edc3d261d6"
binding = "DB"
database_name = "closetcity-db"

[[env.production.r2_buckets]]
bucket_name = "closetcity-storage"
binding = "R2"

[[env.production.kv_namespaces]]
binding = "JOBS"
id = "fb3079a868274895b2386fcd4ad259cc"

[env.production.ai]
binding = "AI"
